
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Mon Oct 14 08:29:03 MDT 2002
//----------------------------------------------------

package geomdir.applied;

/** CUP generated class containing symbol constants. */
public class EXsym {
  /* terminals */
  public static final int OpenOp = 32;
  public static final int proportion = 26;
  public static final int minus = 3;
  public static final int inverse = 12;
  public static final int cross = 30;
  public static final int negation = 7;
  public static final int err = 17;
  public static final int exp = 11;
  public static final int magnitude = 15;
  public static final int ImagGradPart = 28;
  public static final int prod = 4;
  public static final int power = 22;
  public static final int TraceGraph = 25;
  public static final int eof = 16;
  public static final int dlikeProp = 6;
  public static final int div = 5;
  public static final int EOF = 0;
  public static final int Rparen = 10;
  public static final int digit = 33;
  public static final int square = 20;
  public static final int dot = 29;
  public static final int ScalGradPart = 27;
  public static final int wedge = 31;
  public static final int assign = 23;
  public static final int variable = 19;
  public static final int error = 1;
  public static final int period = 18;
  public static final int plus = 2;
  public static final int Lparen = 9;
  public static final int boxPlus = 13;
  public static final int boxMinus = 14;
  public static final int compare = 24;
  public static final int sqrt = 21;
  public static final int uplus = 8;
}

