
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Sat Feb 19 08:05:29 MST 2005
//----------------------------------------------------

package geomdir.engine;

/** CUP generated class containing symbol constants. */
public class GEsym {
  /* terminals */
  public static final int eof = 41;
  public static final int Comma = 34;
  public static final int basis2 = 27;
  public static final int vminus = 5;
  public static final int basis1 = 26;
  public static final int uplus = 12;
  public static final int sinh = 18;
  public static final int DeCastBlossomLeftComp = 35;
  public static final int Lparen = 13;
  public static final int plus = 2;
  public static final int basis12 = 28;
  public static final int cos = 16;
  public static final int cross = 9;
  public static final int minus = 3;
  public static final int cosh = 19;
  public static final int DeCastBlossomRight = 38;
  public static final int Rparen = 14;
  public static final int DeCastLeft = 39;
  public static final int sin = 17;
  public static final int pi = 29;
  public static final int CompObj = 44;
  public static final int inverse = 21;
  public static final int NumConst = 45;
  public static final int Lbrak = 32;
  public static final int EOF = 0;
  public static final int prod = 6;
  public static final int error = 1;
  public static final int Lbrac = 30;
  public static final int DeCastRight = 40;
  public static final int negation = 11;
  public static final int UnitOf = 24;
  public static final int ln = 25;
  public static final int wedge = 10;
  public static final int DeCastBlossomRightComp = 36;
  public static final int magnitude = 22;
  public static final int variable = 46;
  public static final int String = 48;
  public static final int DeCastBlossomLeft = 37;
  public static final int vplus = 4;
  public static final int reverse = 20;
  public static final int Rbrak = 33;
  public static final int PhasToVect = 23;
  public static final int PlugOp = 47;
  public static final int Rbrac = 31;
  public static final int space = 43;
  public static final int err = 42;
  public static final int div = 7;
  public static final int exp = 15;
  public static final int dot = 8;
}

