
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Sat Feb 19 08:13:51 MST 2005
//----------------------------------------------------

package verdantium.mathimage;

/** CUP generated class containing symbol constants. */
public class SEval {
  /* terminals */
  public static final int EndBold = 13;
  public static final int BeginSup = 6;
  public static final int BeginHat = 18;
  public static final int BeginBoldUp = 16;
  public static final int BeginBold = 12;
  public static final int BeginUpright = 14;
  public static final int EndSub = 9;
  public static final int PassThrough = 27;
  public static final int EndBox = 11;
  public static final int EndCursor = 21;
  public static final int LinearLayout = 28;
  public static final int EndBelow = 5;
  public static final int BeginSub = 8;
  public static final int iterm = 26;
  public static final int BeginBox = 10;
  public static final int eof = 25;
  public static final int BeginBelow = 4;
  public static final int EndBoldUp = 17;
  public static final int EndApply = 31;
  public static final int FormattedLayout = 29;
  public static final int BeginTagColor = 23;
  public static final int EndColor = 22;
  public static final int EOF = 0;
  public static final int term = 24;
  public static final int BeginApply = 30;
  public static final int error = 1;
  public static final int EndAbove = 3;
  public static final int EndUpright = 15;
  public static final int BeginAbove = 2;
  public static final int BeginCursor = 20;
  public static final int EndSup = 7;
  public static final int EndHat = 19;
}

